"""Initial_db

Revision ID: 4e846a8831ef
Revises: 
Create Date: 2020-08-23 18:07:23.834522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e846a8831ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('pnCodCliente', sa.Integer(), nullable=False),
    sa.Column('dcNroDoc', sa.String(), nullable=True),
    sa.Column('dcNombre', sa.String(), nullable=True),
    sa.Column('dnDeudaSBS', sa.Numeric(), nullable=True),
    sa.Column('dcPuntSentinel', sa.String(), nullable=True),
    sa.Column('dnIndicador', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('pnCodCliente')
    )
    op.create_table('solicitud',
    sa.Column('pnCodSol', sa.Integer(), nullable=False),
    sa.Column('fnCodCliente', sa.Integer(), nullable=False),
    sa.Column('dnMonto', sa.Numeric(), nullable=True),
    sa.Column('dbAprobado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fnCodCliente'], ['cliente.pnCodCliente'], ),
    sa.PrimaryKeyConstraint('pnCodSol')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitud')
    op.drop_table('cliente')
    # ### end Alembic commands ###
